params:
  # these are for the OpenGraph/Twitter embeds in Hugo
  description: A website
  #bannerContent: some text

  # these are for favicons
  faviconICO: favicon.ico
  faviconPNG: favicon.png

  footer: |-
    Email: davidgroot60@gmail.com

    Links:

    [Braincancer.org](https://braincancer.org)

    [Victory in the Valley](https://example.com)

    Social Media:

    Facebook Twitter Instagram

    Source Code:

    https://github.com/BBaoVanC/brainman.org



title: Brainman
baseURL: https://brainman.org
defaultContentLanguage: en
enableRobotsTXT: true
#paginate: 5
paginate: 3

taxonomies:
  category: categories
  tag: tags

author:
  name: David Groot

markup:
  highlight:
    #noClasses: false
    lineNos: true

# see https://gohugo.io/about/hugo-and-gdpr/#all-privacy-settings
privacy:
  googleAnalytics:
    disable: true

  twitter:
    enableDNT: true

  vimeo:
    enableDNT: true

  youtube:
    privacyEnhanced: true
