baseURL: https://brainman.org
defaultContentLanguage: en
sectionPagesMenu: main
enableRobotsTXT: true
paginate: 5
enableGitInfo: true

taxonomies:
  category: categories
  tag: tags

author:
  name: David Groot

markup:
  highlight:
    #noClasses: false
    lineNos: true

params:
  # these are for the OpenGraph/Twitter embeds in Hugo
  description: A website

  # these are for favicons (unset by default)
  faviconICO: favicon.ico
  faviconPNG: favicon.png

  # show reading time (enabled by default)
  #readingtime: true

  # used for "View source" (unset by default)
  gitFileURL: https://github.com/BBaoVanC/bbaovanc.com/blob/master
  gitFileIcon: code

# see https://gohugo.io/about/hugo-and-gdpr/#all-privacy-settings
privacy:
  googleAnalytics:
    disable: true

  twitter:
    enableDNT: true

  vimeo:
    enableDNT: true

  youtube:
    privacyEnhanced: true

languages:
  en:
    languageName: English
    title: Brainman
    weight: 1

#  es:
#    languageName: Español
#    title: sitio web de bbaovanc
#    weight: 2
#    params:
#      description: Mi sitio web personal
